title: Lethal Company Modding
description: Thunderstore Community
theme: just-the-docs
color_scheme: dark
url: https://lethalcompanymodding.github.io/Thunderstore/

aux_links:
Discord: discord.gg/lcmod

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

callouts_level: quiet # or loud
callouts:
  important:
    title: Important!
    color: orange
  new:
    title: New!
    color: green
  note:
    title: Notice!
    color: yellow
  warning:
    title: Warning!
    color: red

search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
